spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?stringtype=unspecified
    username: postgres
    password: postgres
    hikari:
      register-mbeans: true

springdoc:
  packages-to-scan: com.devdynamos.controller
  paths-to-match: /**